labels: [idea]

body:
  - type: markdown
    attributes:
      value: |
        Share your ideas for new features or improvements!

  - type: textarea
    attributes:
      label: Idea Description
      description: Describe your idea
      placeholder: What's your idea?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem or Use Case
      description: What problem does this solve or what use case does it enable?
      placeholder: Why is this needed?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How would you implement this idea?
      placeholder: How would this work?

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context, examples, or screenshots
      placeholder: Add any other context here...
