name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: [enhancement, needs-triage]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions...

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which component would this affect?
      options:
        - Database Schema
        - Kubernetes Manifests
        - Shell Scripts
        - Docker Configuration
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocking
        - High - Important
        - Medium - Nice to have
        - Low - Optional
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: How would you use this feature?...
    validations:
      required: true

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this introduce breaking changes?
      options:
        - label: This feature would introduce breaking changes
          required: false

  - type: textarea
    id: security
    attributes:
      label: Security Implications
      description: Are there any security considerations?
      placeholder: Describe any security implications...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
      placeholder: Add any other context here...
