name: Security Vulnerability
description: Report a security vulnerability (use Security Advisories for critical issues)
title: "[Security]: "
labels: [security, needs-triage]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please use
        [GitHub Security Advisories](https://github.com/Recipe-Web-App/client-database/security/advisories/new)
        instead of creating a public issue.

        This template is for lower-severity security improvements or concerns.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low - Minimal risk
        - Medium - Moderate risk
        - High - Significant risk (consider Security Advisory)
        - Critical - Severe risk (use Security Advisory instead)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern
      placeholder: What is the security issue?...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - SQL Injection
        - Access Control
        - Authentication/Authorization
        - Data Exposure
        - Configuration Issue
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this is exploited?
      placeholder: Describe the potential impact...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this be reproduced?
      placeholder: |
        1. Step 1...
        2. Step 2...
      render: markdown

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which components are affected?
      placeholder: List affected components...

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Security disclosure agreement
      options:
        - label: I understand this issue will be publicly visible
          required: true
        - label: I confirm this is not a critical vulnerability (critical issues should use Security Advisories)
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context
      placeholder: Add additional context...
